### ISSUE TITLE
Can't start server properly

### ISSUE THREAD

**Issue by ohrie** [ogre/tilemaker_config#1]
When i run the server.py i can't access the maptiles in browser.

It says:
`Error: 404 Not Found

Sorry, the requested URL 'http://localhost:3000/hab.html' caused an error:

Not found: '/hab.html'`

**Comment by michalfratczak** [comment]
I'm not in front of my machine, but I think the file was renamed to index.html
You can fix this line: https://github.com/ogre/tilemaker_config/blob/master/server.py#L77
Or open index.html directly from the project folder.

**Comment by ohrie** [comment]
Yeah, i tried that, but didn't worked. I will try it again!

**Comment by michalfratczak** [comment]
Ok, I made some adjustments, get last commit and retry.
You have to start like this: server.py /path/to/tiles
Look into readme.md again and make sure your tiles directory structure is the same as defined in index.html style. Nonexisting tile files will print in red in console.
